package com.example.llm.service.proxy;

import com.example.llm.model.dto.ChatRequest;
import com.example.llm.model.dto.ChatResponse;
import dev.langchain4j.data.document.Metadata;
import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingMatch;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class LlmOptimizationService {

    private final EmbeddingModel embeddingModel;
    private final EmbeddingStore<TextSegment> embeddingStore;
    private static final double SIMILARITY_THRESHOLD = 0.95;

    /**
     * 3.1 Advanced Semantic Caching with Model Isolation
     * Only returns results generated by the same model to ensure consistency.
     */
    public ChatResponse checkSemanticCache(ChatRequest request) {
        String lastMessage = getUserLastMessage(request);
        if (lastMessage.isEmpty()) return null;

        Embedding queryEmbedding = embeddingModel.embed(lastMessage).content();

        // Search in vector store
        List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.findRelevant(queryEmbedding, 5, SIMILARITY_THRESHOLD);

        for (EmbeddingMatch<TextSegment> match : relevant) {
            String cachedModel = match.embedded().metadata().getString("model");
            
            // Model Isolation: Only hit if the cached model matches the current request model
            if (request.getModel().equals(cachedModel)) {
                String cachedJson = match.embedded().metadata().getString("response_json");
                log.info("🚀 Model-Aware Cache Hit! Model: {} | Similarity: {}", cachedModel, match.score());
                
                try {
                    return new com.fasterxml.jackson.databind.ObjectMapper().readValue(cachedJson, ChatResponse.class);
                } catch (Exception e) {
                    log.error("Failed to deserialize cached response", e);
                }
            }
        }
        return null;
    }

    public void saveToCache(ChatRequest request, ChatResponse response) {
        String lastMessage = getUserLastMessage(request);
        if (lastMessage.isEmpty()) return;

        try {
            String responseJson = new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(response);
            
            // Store text, embedding, and model-specific metadata
            TextSegment segment = TextSegment.from(lastMessage, Metadata.from("response_json", responseJson)
                    .add("model", request.getModel())); // Tie cache to specific model
            
            Embedding embedding = embeddingModel.embed(lastMessage).content();
            
            embeddingStore.add(embedding, segment);
            
            // Persist
            ((InMemoryEmbeddingStore<TextSegment>) embeddingStore).serializeToFile(Paths.get(com.example.llm.config.LangChain4jConfig.CACHE_FILE));
            
            log.info("💾 Saved results for model [{}] to persistent vector store.", request.getModel());
        } catch (Exception e) {
            log.error("Failed to save to semantic cache", e);
        }
    }

    private String getUserLastMessage(ChatRequest request) {
        return request.getMessages().stream()
                .filter(m -> "user".equals(m.getRole()))
                .map(ChatRequest.Message::getContent)
                .reduce((first, second) -> second)
                .orElse("");
    }

    /**
     * 3.2 Prompt Compression (Redundancy Removal)
     */
    public void compressPrompt(ChatRequest request) {
        log.info("✂️ Compressing prompt for model: {}", request.getModel());
        for (ChatRequest.Message msg : request.getMessages()) {
            if ("user".equals(msg.getRole())) {
                String content = msg.getContent();
                // Simple logic: Remove excessive whitespace and common filler words
                String simplified = content.replaceAll("\\s+", " ").trim();
                msg.setContent(simplified);
            }
        }
    }

    /**
     * 3.4 Dynamic Model Routing
     * Route to cheaper model if intent is simple
     */
    public void routeModel(ChatRequest request) {
        String lastMessage = request.getMessages().stream()
                .map(ChatRequest.Message::getContent)
                .collect(Collectors.joining(" "));

        // Simple logic: if message length < 50 and doesn't contain "code" or "analyze", use mini model
        if (lastMessage.length() < 50 && !lastMessage.toLowerCase().contains("code") && request.getModel().startsWith("gpt-4")) {
            log.info("🔀 Routing to low-cost model (gpt-4o-mini) for simple task");
            request.setModel("gpt-4o-mini");
        }
    }
}
